### ISSUE TITLE
onOutputReceived getIsOutgoing and getChangeAmount is false

### ISSUE THREAD

**Issue by abdulkhamir4** [monero-ecosystem/monero-ts#165]
Hello

My use case is listening to onOutputReceived while also using the same wallet in monero-wallet-gui... when I deposit to my address onOutputReceived returns reasonable results
but when I withdraw via monero-wallet-gui onOutputReceived runs with getIsOutgoing and getChangeAmount false

I assume this is the expected behaviour and there is some other way to achieve what I am trying to do, can anyone point me in the right direction?

**Comment by woodser** [comment]
I haven't tried with this setup, but did you check if onOutputSpent() is called? This would be the outgoing spend.

**Comment by abdulkhamir4** [comment]
seems to me onOutputSpent is not called at all when I do withdraw in monero-wallet-gui - I solved my case by avoiding use of monero-wallet-gui and will be using monero-wallet-cli instead with the sweep_all command, as this avoids creation of change and therefore no calling of onOutputReceived

**Comment by woodser** [comment]
Yeah I suspect because the keys are loaded in separate wallets which don't have access to each other's local state, this is expected behavior from monero-project.

A workaround could be to manually fetch the corresponding transaction in onOutputReceived() and check if it has an outgoing transfer, then you know the incoming output is change or an internal transfer.
